# Generated by Django 5.2.5 on 2026-04-24 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
