# Generated by Django 5.2.5 on 2026-05-04 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_remove_produto_preco_produto_estoque_minimo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemvenda',
            name='lucro',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='itemvenda',
            name='preco_custo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='venda',
            name='juros_percentual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='venda',
            name='parcelado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venda',
            name='quantidade_parcelas',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='venda',
            name='total_com_juros',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='ParcelaVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vencimento', models.DateField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('paga', 'Paga'), ('atrasada', 'Atrasada')], default='pendente', max_length=10)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.venda')),
            ],
        ),
        migrations.AddField(
            model_name='financeiro',
            name='parcela',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.parcelavenda'),
        ),
    ]
