# Generated by Django 5.2.5 on 2026-05-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0012_despesa_financeiro_despesa'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='preco_venda',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='produto',
            name='data_ultima_compra',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
