# Generated by Django 5.2.5 on 2026-05-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0013_compra_preco_venda_produto_data_ultima_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='fornecedor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
