# Generated by Django 5.2.5 on 2026-05-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0014_compra_fornecedor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parcelavenda',
            options={'ordering': ['vencimento']},
        ),
        migrations.AddField(
            model_name='venda',
            name='status',
            field=models.CharField(choices=[('ativa', 'Ativa'), ('cancelada', 'Cancelada')], default='ativa', max_length=20),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='parcelavenda',
            unique_together={('venda', 'numero')},
        ),
    ]
