# Generated by Django 5.2.5 on 2026-05-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0019_alter_compra_fornecedor_alter_produto_fornecedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='fornecedor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='fornecedor',
            field=models.CharField(blank=True, default='Não informado', max_length=100, null=True),
        ),
    ]
