# Generated by Django 5.2.5 on 2026-05-06 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0020_alter_compra_fornecedor_alter_produto_fornecedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='fornecedor_cadastro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras', to='clientes.fornecedor'),
        ),
        migrations.AddField(
            model_name='produto',
            name='fornecedor_cadastro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='clientes.fornecedor'),
        ),
    ]
