# Generated by Django 5.2.5 on 2026-05-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0021_compra_fornecedor_cadastro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='localizacao',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
