# Generated by Django 5.2.5 on 2026-06-06 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0027_venda_forma_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='quantidade',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='itemvenda',
            name='quantidade',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='produto',
            name='estoque_minimo',
            field=models.DecimalField(decimal_places=3, default=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='produto',
            name='quantidade',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
