# Generated by Django 5.2.5 on 2026-05-01 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeiro',
            name='compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.compra'),
        ),
        migrations.AddField(
            model_name='financeiro',
            name='venda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.venda'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='data',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='financeiro',
            name='data',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='venda',
            name='data',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
