# Generated by Django 5.2.5 on 2026-05-04 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_itemvenda_lucro_itemvenda_preco_custo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelavenda',
            name='baixado',
            field=models.BooleanField(default=False),
        ),
    ]
