# Generated by Django 5.2.5 on 2026-05-05 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0015_alter_parcelavenda_options_venda_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='fornecedor',
            field=models.CharField(default='Não informado', max_length=100),
        ),
    ]
