# Generated by Django 5.2.5 on 2026-06-05 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0024_alter_cliente_cpf_alter_cliente_telefone'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendaFiado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('quitada', 'Quitada')], default='aberta', max_length=20)),
                ('data', models.DateField(auto_now_add=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('venda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.venda')),
            ],
        ),
        migrations.CreateModel(
            name='PagamentoFiado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField(auto_now_add=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('venda_fiado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='clientes.vendafiado')),
            ],
        ),
    ]
